### ISSUE TITLE
PDF should be built in CircleCI, possible with auto-version.

### ISSUE THREAD

**Issue by kse-clearhaus** [clearhaus/cake-legislation#3]
But how should we distribute the PDF then?

**Comment by jsmpereira** [comment]
> But how should we distribute the PDF then?

How about something like https://github.com/Villanuevand/deployment-circleci-gh-pages?

**Comment by hovmand** [comment]
Post it to Slack.

**Comment by cbobach** [comment]
Fixed by https://github.com/clearhaus/cake-legislation/commit/306823509ddba88e91512b2644fbe2cbb2c0c92a
